version: "3"
services:
  paypal-project-frontend:
    build: ./frontend
    ports:
      - 4173:4173
    environment:
      - VITE_CLIENT_ID=AUqjGvP_0hqXOdPYM8CD6KaQ9UlrdJ6ak3Bkf_bhP5dl-JwJTNNleve1HoYOc7O9WmtZlwM0jc8pL5pF
      - VITE_BACKEND_URL=https://paypal-backend-3h60.onrender.com
    depends_on:
      - paypal-project-backend
    volumes:
      - ./:/app
  paypal-project-backend:
    build: ./backend
    ports:
      - 8888:8888
    environment:
      - CLIENT_ID=AUqjGvP_0hqXOdPYM8CD6KaQ9UlrdJ6ak3Bkf_bhP5dl-JwJTNNleve1HoYOc7O9WmtZlwM0jc8pL5pF
      - SECRET_ID=ELpPA9GjnsdW0cSjLgNwKbXZueTVmUVbP1XS7JZ61gcUQMh3TOUdeRfKbZ7_A1Coj0lkxoWsDNSUvh5B
      - BASE_URL_PAYPAL=https://api-m.sandbox.paypal.com
      - NODE_ENV=developing
      - PORT=8888
      - HOST="0.0.0.0"
    volumes:
      - ./:/app
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true